// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8GdIN_q2rwOCLCv8gwXmRe8TkO2I_E_g',
    appId: '1:508186117931:web:df970dd683b1ff27d9676e',
    messagingSenderId: '508186117931',
    projectId: 'mytravelbuddy-ea0e6',
    authDomain: 'mytravelbuddy-ea0e6.firebaseapp.com',
    storageBucket: 'mytravelbuddy-ea0e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPtFKaA51B9pouBR9JJYM4z6rZFCunZY',
    appId: '1:508186117931:android:31ae154f996f7c15d9676e',
    messagingSenderId: '508186117931',
    projectId: 'mytravelbuddy-ea0e6',
    storageBucket: 'mytravelbuddy-ea0e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5oJGz0-50N0o6kLA8i3_niUUT8gLSgc',
    appId: '1:508186117931:ios:75ba87810d9d8aedd9676e',
    messagingSenderId: '508186117931',
    projectId: 'mytravelbuddy-ea0e6',
    storageBucket: 'mytravelbuddy-ea0e6.appspot.com',
    iosClientId: '508186117931-61kpd1uko177sbieuud6ru38epjhbal1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytravelbuddyapp',
  );
}
